// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvqDF3_g7bToCTwkZEgPORhDAWc0DYtRs',
    appId: '1:310674473443:web:2edee27aa782d1130560d6',
    messagingSenderId: '310674473443',
    projectId: 'billetera-d463a',
    authDomain: 'billetera-d463a.firebaseapp.com',
    storageBucket: 'billetera-d463a.firebasestorage.app',
    measurementId: 'G-GJYHLC16SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtMaaDFhVj6dcUJhbs4OOmQSORpnRrdGE',
    appId: '1:310674473443:android:029ccec26e224d150560d6',
    messagingSenderId: '310674473443',
    projectId: 'billetera-d463a',
    storageBucket: 'billetera-d463a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_DusRhruOnOjwm4kE2JT9KlmRK5xGTE',
    appId: '1:310674473443:ios:69d22446b4c911fc0560d6',
    messagingSenderId: '310674473443',
    projectId: 'billetera-d463a',
    storageBucket: 'billetera-d463a.firebasestorage.app',
    iosClientId: '310674473443-hslsf58lfp59904akfh14rv5mb1l9lhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.billeteraFluter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_DusRhruOnOjwm4kE2JT9KlmRK5xGTE',
    appId: '1:310674473443:ios:69d22446b4c911fc0560d6',
    messagingSenderId: '310674473443',
    projectId: 'billetera-d463a',
    storageBucket: 'billetera-d463a.firebasestorage.app',
    iosClientId: '310674473443-hslsf58lfp59904akfh14rv5mb1l9lhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.billeteraFluter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvqDF3_g7bToCTwkZEgPORhDAWc0DYtRs',
    appId: '1:310674473443:web:9d248e190d85489f0560d6',
    messagingSenderId: '310674473443',
    projectId: 'billetera-d463a',
    authDomain: 'billetera-d463a.firebaseapp.com',
    storageBucket: 'billetera-d463a.firebasestorage.app',
    measurementId: 'G-G7MRVS39Y1',
  );
}
